# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOT-Subscriber' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOT-Subscriber
  pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
  pod 'OpenSSL-Universal'
  
end
